#!/bin/bash -e
if [ `whoami` != 'root' ]; then
	echo "Need to be root" >&2
	exit 250
fi

if [ -z "$1" ]; then
	echo "Missing partition path (/dev/sdb2?)" >&2
	exit 200
fi

partition=$1

# Create encrypted partition
cryptsetup --verbose --verify-passphrase luksFormat $partition
cryptsetup luksOpen $partition my_usb

# Create the ext3 filesystem, and label it "persistence".
mkfs.ext4 -L persistence /dev/mapper/my_usb
e2label /dev/mapper/my_usb persistence

# Create a mount point, mount our new encrypted partition there, set up the persistence.conf file, and unmount the partition.
mkdir -p /mnt/my_usb
mount /dev/mapper/my_usb /mnt/my_usb
echo '/ union' > /mnt/my_usb/persistence.conf
umount /dev/mapper/my_usb

# Close the encrypted channel to our persistence partition.
cryptsetup luksClose /dev/mapper/my_usb

# Remove previously created directory
if [ -d /mnt/my_usb ]; then
	rmdir /mnt/my_usb
fi

exit 0
