#!/bin/bash -e

function _colored_text {
	no_newline=false

	local OPTIND opt=1		# variable needs to be imported into function
	while getopts ':n' opt; do	# leading ':' suppresses automatic error handling, thus allowing *) section
		case "${opt}" in
			n)
				no_newline=true
				;;
			\?)
				echo -e "\033[1;31mError in _colored_text, unknown flag \"$OPTARG\"\033[m" 1>&2
				exit 255		# will exit shell if called directly in interactive mode
				;;
		esac
	done
	shift $((OPTIND-1))

	if $no_newline; then
		echo -ne "\033[$1$2\033[m"
	else
		echo -e "\033[$1$2\033[m"
	fi
}
