#!/bin/bash -e

if [ -z "$(git status --porcelain)" ]; then
	echo 'Nothing to commit. Exiting'
	exit 0
fi

git add .
git status

read -p 'Reason: ' r

if [ -z "$r" ]; then
	r="Quick commit - `date +%d%m%y`"
	echo "Using default commit message: $r"
fi

git commit -m "$r"
git push
