#!/bin/bash -e

source /scripts/lib/colored-text

if [ -z "$(git status --porcelain)" ]; then
	echo 'Nothing to commit. Exiting.'
	exit 0
fi

git add .
git status

_color_n $_TEXT_STYLE_NORMAL $_TEXT_COLOR_BLUE $_TEXT_BACKGROUND_NONE 'Reason: '
read r

if [ -z "$r" ]; then
	r="Quick commit - `date +%d%m%y`"
	_color_n $_TEXT_STYLE_NORMAL $_TEXT_COLOR_YELLOW $_TEXT_BACKGROUND_NONE "Using default commit message: "
	_color_n $_TEXT_STYLE_ITALIC $_TEXT_COLOR_YELLOW $_TEXT_BACKGROUND_NONE "$r"
fi

git commit -m "$r"
git push
