#!/bin/bash -e

source $SCRIPTS/lib/messages

if [ -z "$(git status --porcelain)" ]; then
	echo 'Nothing to commit. Exiting.'
	exit 0
fi

git add .
git status

r=`_msg_ask 'Reason'`

if [ -z "$r" ]; then
	r="Quick commit - `date +%d%m%y`"
	_msg_warning "Using default commit message" "$r"
fi

git commit -m "$r"
git push
