#!/bin/bash

# Check if we have sufficient permissions
if [ `whoami` != "root" ]; then
	echo "Need to be root." >&2
	exit 250
fi


# FLAGs
FLAG_NoUpdate=false
FLAG_DownloadOnly=false


# Get FLAGs
while getopts ":dhn" opt; do
	case $opt in
	d)
		FLAG_DownloadOnly=true
		;;
	h)
		echo -e "Flags:"
		echo -e "\t-h\tThis help message"
		echo -e "\t-d\tDownload only mode, doesn't install updates"
		echo -e "\t-n\tSkip \`apt-get update\` command"
		exit 0;
		;;
	n)
		FLAG_NoUpdate=true
		;;
	\?)
		echo "Invalid option: -$OPTARG" >&2
		echo "Use -h for help" >&2
		exit 200
		;;
	esac
done


# Update
if [ $FLAG_NoUpdate == false ]; then
	apt update
fi

# Upgrade
if [ $FLAG_DownloadOnly == true ]; then
	apt dist-upgrade -dy
else
	apt dist-upgrade -y

	# Clean
	apt autoremove -y
	apt autoclean
fi

exit 0
