#!/bin/bash -e

FILE="$1"

if [ -z "$FILE" ]; then
	echo "Usage:" >&2
	echo -e "\t"	"$0 <file>" >&2
	exit 200
fi

if [ ! -f "$FILE" ]; then
	echo "File $1 does not exist." >&2
	exit 1
fi


# Get and set tags
echo "File: $FILE"
read -p "Artist: " ARTIST
	id3v2 "$FILE" -a "$ARTIST"
read -p "Album: " ALBUM
	id3v2 "$FILE" -A "$ALBUM"
read -p "Title: " TITLE
	id3v2 "$FILE" -t "$TITLE"
read -p "Genre (num): " GENRE
	id3v2 "$FILE" -g "$GENRE"
read -p "Year: " YEAR
	id3v2 "$FILE" -y "$YEAR"
read -p "Track: " TRACK
	id3v2 "$FILE" -T "$TRACK"

# Show tags
echo
id3v2 -l "$FILE"

exit 0
