#!/bin/bash

site='http://kissanime.ru'
browser='firefox'

url_file=
out_file=


if [ -z "$1" -o -z "$2" ]; then
	echo -e "Usage:" >&2
	echo -e "\t"	"$0 <url file> <out file>" >&2
	exit 200
fi

if [ ! -f "$1" ]; then
	echo "File $1 does not exist" >&2
	exit 1
fi

if [ ! -f "$2" ]; then
	echo "File $2 does not exist" >&2
	exit 1
fi

clear
# open firefox
	$browser $site 2>/dev/null 1>/dev/null &
# wait for login
	echo -n "Press Enter to begin... "
	read
# open out file
	gnome-terminal			# open new terminal
	sleep 1
	xdotool type "nano $2"		# open file in nano
	xdotool key Return
#	xdotool key Down		# skip first line


while read url; do
	# open tab
		$browser "$url" 2> /dev/null
		sleep 10

	# search url
		xdotool key shift+Tab ctrl+f
		sleep 0.5
		xdotool type ".mp4"
		sleep 0.5
		xdotool key Escape

	# copy url
		# right click
			xdotool key shift+F10
		sleep 0.5
		# select "copy url location"
#			xdotool key Down Down Down Down Down Down Down
#			xdotool key Return
			xdotool key a
		sleep 0.5

	# get back to nano
		xdotool key alt+Tab
		sleep 0.5
	# paste url
		xdotool key ctrl+shift+v
		sleep 0.5
	# get ready for writing the next line
		xdotool key Down #Down
		sleep 0.5

	# get back to firefox
		xdotool key alt+Tab
		sleep 0.5
	# close tab
		xdotool key ctrl+F4
		sleep 0.5
done < $1


# get back to nano	### [, save and close it]
	xdotool key alt+Tab
exit 0


	xdotool key ctrl+o Return
	xdotool key ctrl+x
	sleep 0.2
# close also the terminal it was running on
	xdotool type "exit"
	xdotool key Return

exit 0
