#!/bin/bash -e

python -m dav_tools.messages success "IP Address: $(hostname -I)"
# python -m dav_tools.messages success "External IP Address: $($SCRIPTS/network/ip-external)"

echo
python -m dav_tools.messages info 'Executing Speedtest...'
# speedtest=$(speedtest --simple --bytes)
speedtest=$(speedtest --json | jq '.ping,.download,.upload')
    ping=$(echo "$speedtest" | cut -d ',' -f 1)
download=$(echo "$speedtest" | cut -d ',' -f 2)
  upload=$(echo "$speedtest" | cut -d ',' -f 3)

python -m dav_tools.messages success "Ping: ${ping} ms"
python -m dav_tools.messages success "Download: ${download} Mbps"
python -m dav_tools.messages success "Upload: ${upload} Mbps"

