#!/bin/bash -e
# Activate the virtual environment
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../venv/bin/activate"

python -m dav_tools.requirements --root --os Linux

sed -i 's/#HandleLidSwitch=.*/HandleLidSwitch=ignore/' /etc/systemd/logind.conf
systemctl restart systemd-logind.service

python -m dav_tools.messages success 'Closing the lid will now do nothing'
