#!/bin/bash
# Activate the virtual environment
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../venv/bin/activate"

# Note
#   Manual error handling: no need for -e flag

python -m dav_tools.requirements --root --os Linux

function cleanup {
	rm -v .sudoers-tmp
	exit $1
}

if [ -z "$1" ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

cp -v /etc/sudoers .sudoers-tmp

command="$1 ALL=(ALL) NOPASSWD:ALL"

if ( grep -q "$command" .sudoers-tmp ); then
	echo 'User already has correct permissions'
	cleanup 0
fi

echo "$command" >> .sudoers-tmp

chmod 0440 .sudoers-tmp

visudo --check --perms --owner --strict .sudoers-tmp
status=$?

if [ $status -eq 0 ]; then
	mv -v .sudoers-tmp /etc/sudoers
else
	echo 'Error. Aborting.'
	cleanup 1
fi

python -m dav_tools.messages success "User '$1' can now perform passwordless sudo"
