#!/bin/bash

USAGE="$0 <command> [delay ...]"


if [ "$#" == "0" ]; then
	echo "$USAGE"
	exit 1
fi

command="$1"
shift

while (( "$#" )); do
	"$command"
	ret=$?

	if [[ ret -ne 0 ]]; then
		echo "Command exit status: $ret"
		exit $ret
	fi

	echo "Sleeping for $1..."
	sleep "$1"

	shift
done
