#!/bin/bash

files=()

for f in `ls -a $1`; do
	if [ -f "$f" -a -w "$f" ]; then
		files+=("$f")
	fi
done

if [ ${#files[@]} -gt 0 ]; then
	ls -lhv --color=auto --group-directories-first ${files[@]}
fi
