#!/bin/bash -e

python -m dav_tools.requirements --root --os Linux

if [ "$#" -lt 1 ]; then
	dir=$(mktemp -d)
	_msg_info "Using folder $dir"
else
	dir="$1"
fi

# install minimal debian distro
debootstrap focal $dir

# prepare for chroot
mount --verbose --bind /dev $dir/dev
mount --verbose --bind /dev/pts $dir/dev/pts
mount --verbose --bind /proc $dir/proc
mount --verbose --bind /sys $dir/sys

# copy mount-unmount scripts
cp -v /scripts//util/.make-chroot-mount $dir/mount
cp -v /scripts//util/.make-chroot-umount $dir/umount
cp -v -r /scripts/ $dir/
/scripts//config/setup_bash.py $dir/root

chroot $dir
