#!/bin/bash -e

if [ "$#" -lt 2 ]; then
	echo "$0 <iso-file> <mount-dir> [offset]"
	exit 1
fi

if [ -z "$3" ];then
	offset=0
else
	offset=$(expr 512 \* "$3")	# "*" must be escaped to avoid shell expansion
fi

mount -o loop,offset=$offset "$1" "$2"
