#!/bin/bash -e
# Activate the virtual environment
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../venv/bin/activate"

if [ $# -lt 1 ]; then
	python -m dav_tools.messages info 'Setting port to 41144'
	port=41144
else
	port=$1
fi

nc -vl $port | bunzip2 | dd status=progress
