#!/bin/bash -e

if [ $# -lt 1 ]; then
	python -m dav_tools.messages info "usage: $0 <host> [port]"
	exit 1
fi

host=$1


if [ -z "$2" ]; then
	python -m dav_tools.messages info 'Setting port to 41144'
	port=41144
else
	port=$2
fi


dd bs=900K status=progress | bzip2 -9 | nc -v $host $port
