#!/bin/bash -e

python -m dav_tools.requirements --root --os Linux

if [ "$#" -lt 1 ]; then
	echo "usage: $0 <device>"
	exit 1
fi

device="$1"

# format device
mkfs.fat -F 32 -n DAVRESCUE $device
fatlabel $device -i E8092
python -m dav_tools.messages success 'Formatted device'

# mount
dir=$(mktemp -d)
mount $device $dir
python -m dav_tools.messages success 'Mounted device'

# create folders
mkdir -p $dir/EFI/boot
mkdir -p $dir/boot
mkdir -p $dir/iso

# copy config
cp /scripts/rescue/.grub.efi $dir/EFI/boot/bootx64.efi		#cp -v /boot/grub/x86_64-efi/grub.efi $dir/EFI/boot/bootx64.efi
cp -r /scripts/rescue/.grub $dir/boot/grub
python -m dav_tools.messages success 'Copied configuration'

# install GRUB
grub-install --target=x86_64-efi --boot-directory=$dir --efi-directory=$dir --removable $device
python -m dav_tools.messages success 'Installed grub'

# unmount and clean-up
umount $dir
rmdir $dir
python -m dav_tools.messages success 'Unmounted device'

python -m dav_tools.messages info 'Remember to manually copy iso files to /iso folder'
