#!/bin/bash -e

source ${SCRIPTS}/lib/messages


# prints an error message if the effective user is not root
function _require_root() {
	if [ "$EUID" -ne 0 ]; then
		_msg_error 'Script must be run as root user.';
		exit 0
	fi
}

