#!/bin/bash -e

# Failsafe for new installations
if [ -z "$SCRIPTS" ]; then
	SCRIPTS=/scripts
fi

source $SCRIPTS/lib/messages


if [ -z "${1}" ]; then
	DIR="$HOME"
else
	DIR="${1}"
fi


copy(){
	rm -f "${DIR}/${1}"
	ln -s "${SCRIPTS}/config/.bash/${1}" "${DIR}/${1}"
}


copy .bash_aliases
copy .bashrc
copy .dircolors

_msg_success "Bash setup complete ($DIR)"
