#!/bin/bash

source ${SCRIPTS}/lib/messages
source ${SCRIPTS}/lib/user

# Note
#   Manual error handling: no need for -e flag

function cleanup {
	rm -v .sudoers-tmp
	exit $1
}

_require_root

if [ -z "$1" ]; then
	_msg_usage "$0 <username>"
	exit 1
fi

cp -v /etc/sudoers .sudoers-tmp

command="$1 ALL=(ALL) NOPASSWD:ALL"

if ( grep -q "$command" .sudoers-tmp ); then
	_msg_success 'User already has correct permissions'
	cleanup 0
fi

echo "$command" >> .sudoers-tmp

chmod 0440 .sudoers-tmp

visudo --check --perms --owner --strict .sudoers-tmp
status=$?

if [ $status -eq 0 ]; then
	mv -v .sudoers-tmp /etc/sudoers
else
	_msg_error 'Error. Aborting.'
	cleanup 1
fi

_msg_success "User '$1' can now perform passwordless sudo"
