#!/bin/bash

# Note
#   Manual error handling: no need for -e flag

function cleanup {
	rm -v .sudoers-tmp
	exit $1
}

if [ "$EUID" -ne 0 ]; then
	echo 'Script must be run as root user.';
	exit 0
fi

if [ -z "$1" ]; then
	echo "Usage: $0 <username>"
	exit 1
fi

cp -v /etc/sudoers .sudoers-tmp

command="$1 ALL=(ALL) NOPASSWD:ALL"

if ( grep -q "$command" .sudoers-tmp ); then
	echo 'User has already correct permission'
	cleanup 0
fi

echo "$command" >> .sudoers-tmp

chmod 0440 .sudoers-tmp

visudo --check --perms --owner --strict .sudoers-tmp
status=$?

if [ $status -eq 0 ]; then
	mv -v .sudoers-tmp /etc/sudoers
else
	echo 'Error. Aborting.'
	cleanup 1
fi
