#!/bin/bash -e

apt install apache2 mysql-server php libapache2-mod-php php-mysql phpmyadmin php-mbstring php-zip php-gd php-json php-curl -y

mysql <<< "DROP USER IF EXISTS 'dba'@'localhost';"
mysql <<< "CREATE USER 'dba'@'localhost' IDENTIFIED BY 'dav';"
#mysql <<< "GRANT ALL PRIVILEGES ON *.* TO 'dba'@'localhost';"

echo "Created admin account: 'dba'@'localhost', password: 'dav'"
