#!/bin/bash -e

source $SCRIPTS/lib/messages


if [ -z "${1}" ]; then
	DIR="$HOME"
else
	DIR="${1}"
fi


copy(){
	rm -fv "${DIR}/${1}"
	ln -v "${SCRIPTS}/config/${1}" "${DIR}/${1}"
}


copy .bash_aliases
copy .bashrc
copy .dircolors

_msg_done
