#!/bin/bash -e

source ${SCRIPTS}/lib/messages

file=${SCRIPTS}/config/.gnome-terminal-profiles.dconf

dconf load /org/gnome/terminal/legacy/profiles:/ < $file

_msg_success 'Imported terminal profile'
