#!/bin/bash -e

source ${SCRIPTS}/lib/messages
source ${SCRIPTS}/lib/user

_require_root


# Temporary file used by `print()`
tmp=`mktemp`

# Temporary file used by `lshw`
HW=`mktemp`




# Get relevant lines, remove formatting and print them
function print
{
	grep "$1" $HW > $tmp

	while read line; do
		# trim spaces
		line=$(echo $line)
		printf "\t${line#*$1}\n"
	done < $tmp
}





# Save a list of current hardware to a temporary file
lshw -short > $HW

# Print relevant information
_msg_info "Processor:"
	print "processor"
_msg_info "Memory:"
	print "memory"
_msg_info "Graphic Cards:"
	print "display"
_msg_info "Network:"
	print "network"
_msg_info "Disks:"
	print "disk"
_msg_info "Volumes:"
	print "volume"

# remove temporary files
rm -f $TMP $HW

