#!/bin/bash -e

python -m dav_tools.requirements --root --os Linux


# Temporary file used by `print()`
tmp=`mktemp`

# Temporary file used by `lshw`
HW=`mktemp`




# Get relevant lines, remove formatting and print them
function print
{
	grep "$1" $HW > $tmp

	while read line; do
		# trim spaces
		line=$(echo $line)
		printf "\t${line#*$1}\n"
	done < $tmp
}





# Save a list of current hardware to a temporary file
lshw -short > $HW

# Print relevant information
python -m dav_tools.messages info "Processor:"
	print "processor"
python -m dav_tools.messages info "Memory:"
	print "memory"
python -m dav_tools.messages info "Graphic Cards:"
	print "display"
python -m dav_tools.messages info "Network:"
	print "network"
python -m dav_tools.messages info "Disks:"
	print "disk"
python -m dav_tools.messages info "Volumes:"
	print "volume"

# remove temporary files
rm -f $TMP $HW

