#!/bin/bash -e

python -m dav_tools.requirements --root --os Linux

query="SELECT DISTINCT CONCAT(user, ':', authentication_string) FROM mysql.user WHERE authentication_string <> '';"

mysql --skip-column-names <<< "$query"
