#!/bin/bash -e
# Activate the virtual environment
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../venv/bin/activate"

python -m dav_tools.requirements --root --os Linux

unshadow /etc/passwd /etc/shadow
