#!/bin/bash -e
# Activate the virtual environment
SCRIPT_DIR="$(cd "$(dirname "$0")" && pwd)"
source "$SCRIPT_DIR/../venv/bin/activate"

python -m dav_tools.requirements --root --os Linux

query="SELECT DISTINCT CONCAT(user, ':', authentication_string) FROM mysql.user WHERE authentication_string <> '';"

mysql --skip-column-names <<< "$query"
