#!/bin/bash
if [ `whoami` != "root" ]; then
	echo "Need to be root." >&2
	exit 250
fi

# try installing through apt-get...
apt-get install youtube-dl -y

# ... if that fails, install manually
if [ $? != 0 ]; then
	set -e
	cd /usr/local
	wget http://youtube-dl.org/downloads/2014.03.12/youtube-dl-2014.03.12.tar.gz
	tar xzf youtube-dl-2014.03.12.tar.gz
	cd youtube-dl
	ln youtube-dl /bin
	youtube-dl -U
fi

exit 0
