#!/bin/bash

# Define a list of services to check
SERVICES=('ssh' 'fail2ban' 'vsftpd' 'apache2' 'mysql' 'postgresql' 'docker' 'transmission-daemon')


# Function to check service status using if/else
check_service() {
  local service="$1"
  if systemctl is-active --quiet "$service"; then
    echo -e "  [+] $service"
  else
    echo -e "  \e[31m[-] $service\e[0m"
  fi
}


# Iterate over the services and check each one
echo
echo 'Services status:'

for service in "${SERVICES[@]}"; do
  check_service "$service"
done
