#!/bin/bash

# Define a list of services to check
SERVICES=('ssh' 'fail2ban' 'docker' 'nginx' 'postgresql' 'qbittorrent-nox')

echo
echo ' Services status:'

for service in "${SERVICES[@]}"; do
    # Enabled or disabled
    if systemctl is-enabled --quiet "$service" 2>/dev/null; then
        ENABLE_MARK='\e[36m[*]\e[0m'
    else
        ENABLE_MARK='\e[90m[ ]\e[0m'
    fi

    # Active or inactive
    if systemctl is-active --quiet "$service"; then
        SERVICE_COLOR="\e[36m$service\e[0m"  # cyan
    else
        SERVICE_COLOR="\e[90m$service\e[0m"  # gray
    fi

    echo -e "  $ENABLE_MARK $SERVICE_COLOR"
done
