#!/bin/bash

echo
echo ' Docker containers:'

all_containers=$(docker ps -a --format '{{.Names}}')
running_containers=$(docker ps --format '{{.Names}}')

for name in $all_containers; do
  if echo "$running_containers" | grep -q "^$name$"; then
    echo -e "  \e[36m[+] $name\e[0m"
  else
    echo -e "  \e[33m[-] $name\e[0m"
  fi
done
