#!/bin/bash

# Check if the user is root
if [ "$(id -u)" -ne 0 ]; then
    exit 1
fi

echo
echo "=== Fail2ban Banned IPs by Jail ==="

# Get the list of jails from fail2ban-client
jail_list=$(fail2ban-client status | grep "Jail list:" | cut -d: -f2 | tr ',' ' ')
for jail in $jail_list; do 
    # Trim any leading/trailing whitespace
    jail=$(echo $jail)
    # Count the banned IPs by counting the fields in the banned IP list
    count=$(fail2ban-client status "$jail" | grep "Banned IP list:" | awk -F': +' '{print NF-1}')
    echo "$jail: $count"
done

echo "==================================="
