#!/bin/bash -e

# Define the dialog exit status codes
DIALOG_OK=0
DIALOG_CANCEL=1
DIALOG_HELP=2
DIALOG_EXTRA=3
DIALOG_ITEM_HELP=4
DIALOG_ESC=255

# Duplicate (make a backup copy of) file descriptor 1 on descriptor 3
exec 3>&1
trap cleanup 0 1 2 5 15

# Command builder
command='nmap 192.168.1.*'


#############################################################################

function close() {
	echo 'Quitting'
	exit 99
}

function cleanup() {
	echo 'Cleaning up...'
	exec 3>&-
}

function select_action() {
	action=$(dialog --menu 'Select action' 0 0 0 \
		'Host discovery' '' \
		'Port scan' '' \
		2>&1 1>&3)
	case $ret in
		$DIALOG_OK)
			echo "$action"
			;;
		$DIALOG_CANCEL)
			close
			;;
		$DIALOG_ESC)
			close
			;;
	esac
}

function select_scan_type() {
	scan_type=$(dialog --radiolist 'Select scan type' 0 0 0 \
		'-sL' 'List scan' \
		'-sn' 'No port scan' \
		'-Pn' 'No ping' \
		'-PS' 'TCP SYN ping' \
		'-PA' 'TCP ACK ping' \
		'-PU' 'UPD ping' \
		'-PR' 'ARP ping' \
		2>&1 1>&3)
	ret=$?
	case $ret in
		$DIALOG_OK)
			if [ -z "$scan_type" ]; then
				select_scan_type
			else
				echo "$scan_type"
			fi
			;;
		$DIALOG_CANCEL)
			close
			;;
		$DIALOG_ESC)
			close
			;;
	esac
}

function select_speed() {
	speed=$(dialog --radiolist 'Select Speed' 0 0 0 \
		'-T0' 'Paranoid' off \
		'-T1' 'Sneaky' off \
		'-T2' 'Polite' off \
		'-T3' 'Normal' on \
		'-T4' 'Aggressive' off \
		'-T5' 'Insane' off \
		2>&1 1>&3)
	ret=$?
	case $ret in
		$DIALOG_OK)
			echo "$speed"
			;;
		$DIALOG_CANCEL)
			close
			;;
		$DIALOG_ESC)
			close
			;;
	esac
}

#############################################################################

# Select action
action=$(select_action)

if [ "$action" == 'Host discovery' ]; then
	command="$command $(select_scan_type)"
fi

# Select speed
command="$command $(select_speed)"

echo $command


