#!/bin/bash -e

data=`grep 'psk=' /etc/NetworkManager/system-connections/*`

for line in $data; do
	wifi=`echo $line | cut -d : -f 1 | cut -d / -f 5 | cut -d . -f 1`
	password=`echo $line | cut -d : -f 2 | cut -d = -f 2`

	echo -e "$wifi:\t$password"
done
